### ISSUE TITLE
Create bash script to automate retrieval & update of PDG portal

### ISSUE THREAD

**Issue by robyngit** [PermafrostDiscoveryGateway/viz-info#4]
To speed up the process of managing the PDG portal's content, it would be helpful to develop a Bash script that automates the process of retrieving and updating the portal XML doc in both production and test environments using the DataONE API. The current `update-PDG-portal.Rmd` file is helpful in this task, but a bash script will be quicker to run and will require less setup for new users (especially those not familiar with R). 

The script will:

- **Retrieve the Latest Portal Version**: The script should be able to query the DataONE API to find the latest version of the permafrost portal. It should handle both production (`PROD`) and test (`STAGING`) environments.

- **Download Portal XML**: After identifying the latest version, the script should download the corresponding XML document, allowing for local editing.

- **Update Portal XML**: The script should be capable of uploading a modified XML document back to the ADC, thus updating the portal.

- **Command Line Flexibility**: The script should accept command line arguments for different actions (download or update), environments (production or test), and the user's authentication token.

**Comment by mbjones** [comment]
This sounds great. Most of that functionality is already present in the `dataone` R package. All you'd need to do is customize the query function to find the portal of interest. the token, download, and upload code is already there. So a lightweight wrapper around the R client would be straightforward. Also true for the python client I think. Of course, you could do it in curl/bash as well, but there's a fair amount you'd need to do in shell on the upload side to get it to work (like creating/updating a valid sysmeta document).

**Comment by rushirajnenuji** [comment]
[R code scripted](https://github.com/PermafrostDiscoveryGateway/viz-info/blob/main/helpful-code/update-PDG-portal.Rmd) by @robyngit 

Sample [bash script](https://gist.github.com/rushirajnenuji/2562f0a9c620308ed6dce559f4f7e571) from a while ago

Closing this issue out
